version: '3.9'

services:
  web:
    image: form_creator
    container_name: form_creator
    ports:
      - "8000:8000"
    volumes:
      - ./src/db.sqlite3:/app/src/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000
