# Generated by Django 5.1.1 on 2024-10-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("form", "0001_initial"),
        ("report", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formresponse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="processresponse",
            name="completed_forms",
            field=models.ManyToManyField(
                related_name="completed_in_process", to="report.formresponse"
            ),
        ),
        migrations.AddField(
            model_name="processresponse",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="form.process",
            ),
        ),
        migrations.AddField(
            model_name="processresponse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("report_type", "related_object_id")},
        ),
        migrations.AddField(
            model_name="periodicreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodic_reports",
                to="report.report",
            ),
        ),
        migrations.AddField(
            model_name="reportlog",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="report.report",
            ),
        ),
    ]
